spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.6.40:1521:testora
    username: iosm5
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.type: trace
    com.hgicreate.rno.demo: debug